adding all files for color sensor
team422/FRC-22-Rewrite pull request #11
Opened 2022-03-12 02:05 UTC by shoryamalani

2022-03-12 02:48 UTC, WAaron-500 requested changes
Don't use Integer its ugly use int

2022-03-18 03:45 UTC, hadley31 requested changes

2022-03-18 03:45 UTC, hadley31 commented on src/main/java/frc/robot/subsystems/colorSensor/ColorSensor.java
> +    public Integer getProximity(){
```suggestion
    public int getProximity(){
```

2022-03-18 03:45 UTC, hadley31 commented on src/main/java/frc/robot/subsystems/colorSensor/ColorSensorIO.java
> +    public default Integer getProximity() {
```suggestion
    public default int getProximity() {
```

2022-03-18 03:45 UTC, hadley31 commented on src/main/java/frc/robot/subsystems/colorSensor/ColorSensorIORevV3.java
> +    public Integer getProximity(){
```suggestion
    public int getProximity(){
```

2022-03-18 03:45 UTC, hadley31 commented on src/main/java/frc/robot/subsystems/colorSensor/ColorSensorIORevV3.java
> +    private final Color kRedTarget = new Color(0.561, 0.232, 0.114);
```suggestion
    private static final Color kBlueTarget = new Color(0.143, 0.427, 0.429);
    private static final Color kRedTarget = new Color(0.561, 0.232, 0.114);
```

2022-03-18 22:08 UTC, closed without merging