True aaron vision sniper mode
team422/FRC-22-Rewrite pull request #33
Opened 2022-03-29 02:02 UTC by WAaron-500

Too lazy to fix manually just created new branch from main and went from there lmfao

2022-03-29 02:11 UTC, hadley31 requested changes
Looks good, minor changes requested

2022-03-29 02:11 UTC, hadley31 commented on src/main/java/frc/robot/commands/visioncommands/VisionSniperMode.java
> +
```suggestion

    @Override
    public void end() {
        hubCam.setLEDEnabled(false);
    }

```

2022-03-29 02:11 UTC, hadley31 commented on src/main/java/frc/robot/RobotContainer.java
> +        VisionSniperMode RotateToHubAdjustable = new VisionSniperMode(hubCamera, drive, () -> controls.getLeftDriveY());
```suggestion
        VisionSniperMode rotateToHubAdjustable = new VisionSniperMode(hubCamera, drive, () -> controls.getLeftDriveY());
```

2022-03-29 02:11 UTC, hadley31 commented on src/main/java/frc/robot/RobotContainer.java
> +        controls.getAutoAimButton().whileActiveOnce(RotateToHubAdjustable);
```suggestion
        controls.getAutoAimButton().whileActiveOnce(rotateToHubAdjustable);
```

2022-03-29 03:14 UTC, hadley31 approved these changes
lgtm

2022-03-31 02:48 UTC, closed without merging

2022-03-31 02:48 UTC, WAaron-500 commented
this is basically the other PR with less stuff so imma close it