Auto with trajectory
team422/FRC-22-Rewrite pull request #8
Opened 2022-03-10 22:09 UTC by FellStinger

Fun auto times

2022-03-12 13:16 UTC, hadley31 requested changes, later dismissed

2022-03-12 13:16 UTC, hadley31 commented on src/main/java/frc/robot/commands/AutoMotionProfiling.java
> +                maxAcceleration = 20.0;
This is max 2.5 meters per second! That's really fast
```suggestion
                maxVelocity = 0.5;
                maxAcceleration = 1;
```

2022-03-12 13:16 UTC, hadley31 commented on src/main/java/frc/robot/subsystems/drivetrain/DriveBase.java
> +        odometry.update(new Rotation2d(driveIO.getGyroAngle()),
I believe that the `getGyroAngle()` returns the opposite sign
```suggestion
        odometry.update(new Rotation2d(-driveIO.getGyroAngle()),
```

2022-03-12 13:17 UTC, hadley31 commented on src/main/java/frc/robot/subsystems/drivetrain/DriveBase.java
> +    }
Is there any gear ratio we need to account for here?

2022-03-19 19:42 UTC, WAaron-500 approved these changes

2022-03-19 19:44 UTC, SFang-cmd approved these changes

2022-03-19 19:44 UTC, merged